More fixes

diff --git a/.github/workflows/maven-release.yml b/.github/workflows/maven-release.yml
--- a/.github/workflows/maven-release.yml
+++ b/.github/workflows/maven-release.yml
@@ -16,21 +16,26 @@ env:
   DEPLOY_REPO_ID: github-emergentdotorg
   DEPLOY_USERNAME: ${{ secrets.deploy_username }}
   DEPLOY_PASSWORD: ${{ secrets.deploy_password }}
-  DEPLOY_SSH_KEY: ${{ secrets.SSH_MVN_REPO_DEPLOY_KEY }}
 
 jobs:
 
   release:
-    runs-on: ubuntu-latest
+    runs-on: ubuntu-20.04
 
     steps:
       - uses: actions/checkout@v4
-      - name: Set up JDK 1.8
+
+      - name: Set up JDKs
         uses: actions/setup-java@v4
         with:
-          java-version: '1.8'
           distribution: 'temurin'
+          java-version: |
+            8
+          mvn-toolchain-vendor: Eclipse Temurin
           cache: maven
+          server-id: ${{ env.DEPLOY_REPO_ID }}
+          server-username: 'DEPLOY_USERNAME'
+          server-password: 'DEPLOY_PASSWORD'
           settings-path: ${{ github.workspace }} # directory for the settings.xml file
 
       - name: Set up Maven
@@ -38,58 +43,46 @@ jobs:
         with:
           maven-version: 3.8.8
 
-      - name: Set up Maven settings.xml
-        uses: s4u/maven-settings-action@v3.0.0
-        with:
-          path: ${{ github.workspace }}/settings.xml
-          servers: |
-            [{
-              "id": "${{ env.DEPLOY_REPO_ID }}",
-              "username": "${env.DEPLOY_USERNAME}",
-              "password": "${env.DEPLOY_PASSWORD}"
-             },{
-              "id": "github-emergentdotorg",
-              "username": "${env.DEPLOY_USERNAME}",
-              "password": "${env.DEPLOY_PASSWORD}"
-            }]
-
       - name: Release with Maven
         shell: bash
         env:
           RELEASE_PLUGIN_COORDS: org.apache.maven.plugins:maven-release-plugin:3.1.1
         run: |
-          MVN_REL_VER="${{ github.event.inputs.next-release-version }}"
-          MVN_DEV_VER="${{ github.event.inputs.next-snapshot-version }}"
+          NEXT_REL_VER="${{ github.event.inputs.next-release-version }}"
+          NEXT_DEV_VER="${{ github.event.inputs.next-snapshot-version }}"
 
-          echo MVN_REL_VER=$MVN_REL_VER
-          echo MVN_DEV_VER=$MVN_DEV_VER
-          echo RELEASE_PLUGIN_COORDS=$RELEASE_PLUGIN_COORDS
+          echo NEXT_REL_VER=$NEXT_REL_VER
+          echo NEXT_DEV_VER=$NEXT_DEV_VER
+               
+          function getRelProp {
+            grep "^${1}=" release.properties|cut -d'=' -f2
+          }
+          
+          function execMvn {
+            local argsargs=( )
+            local anteargs=( )
+            local postargs=( )
 
-          argargarr=( )
-          argargarr+=( "-Dmaven.javadoc.skip=true" )
+            argsargs+=( "-Dmaven.javadoc.skip=true" )
 
-          dargarr=( )
-          dargarr+=( "-Dresume=false" )
-          dargarr+=( "-DpushChanges=true" )
-          dargarr+=( "-DlocalCheckout=true" )
-          dargarr+=( "-DtagNameFormat=@{project.version}" )
-          dargarr+=( "-DscmCommentPrefix=[GitHub] " )
-          dargarr+=( "-Darguments=${argargarr[*]}" )
+            anteargs+=( "-B" )
+            anteargs+=( "-Dresume=false" )
+            anteargs+=( "-DpushChanges=true" )
+            anteargs+=( "-DlocalCheckout=true" )
+            anteargs+=( "-DtagNameFormat=@{project.version}" )
+            anteargs+=( "-DscmCommentPrefix=[GitHub] " )
+            if [ ! -z "$NEXT_REL_VER" ] ; then anteargs+=( "-DreleaseVersion=$NEXT_REL_VER" ) ; fi
+            if [ ! -z "$NEXT_DEV_VER" ] ; then anteargs+=( "-DdevelopmentVersion=$NEXT_DEV_VER" ) ; fi       
+            anteargs+=( "-Darguments=${argsargs[*]}" )
 
-          if [ ! -z "$MVN_REL_VER" ] ; then
-            dargarr+=( "-DreleaseVersion=$MVN_REL_VER" )
-          fi
-          if [ ! -z "$MVN_DEV_VER" ] ; then
-            dargarr+=( "-DdevelopmentVersion=$MVN_DEV_VER" )
-          fi     
+            postargs+=( "-s" "$GITHUB_WORKSPACE/settings.xml" )
+            mvn "${anteargs[@]}" \
+              "$@" \
+              "${postargs[@]}"
+            rc=$? ; if [ ${rc} -ne 0 ] ; then echo "Error in prepare & perform, exit code was $rc" ; return $rc ; fi
+          }
 
-          pargarr=( "-s" "$GITHUB_WORKSPACE/settings.xml" )
-
-          mvn -B "${dargarr[@]}" \
-            $RELEASE_PLUGIN_COORDS:prepare \
-            $RELEASE_PLUGIN_COORDS:perform \
-            "${pargarr[@]}"
-
+          execMvn $RELEASE_PLUGIN_COORDS:prepare $RELEASE_PLUGIN_COORDS:perform
           rc=$? ; if [ ${rc} -ne 0 ] ; then echo "Error in prepare, exit code was $rc" ; exit $rc ; fi
 
 #          git push --follow-tags --atomic
